### ISSUE TITLE
is VulnDBGen private?

### ISSUE THREAD

**Issue by shervinkh** [squizz617/vuddy#10]
Hi,
Is your VulnDBGen repository private?
I'm doing a research on vulnerabilities and I could really use your vulnerability database or its generator.
The link to the repository is broken. Is there anyway to get it?
Thanks in advance.

**Comment by turned2670** [comment]
I've also encountered this problem before. The link is broken. But if you click the debug branch, its readme.md has figured out steps of getting the vulnerability database.

**Comment by squizz617** [comment]
Hi, sorry for a delayed reply. I've been on a holiday this week.
Currently, the VulnDBGen repository is private, because of some issues related to the patent application.
We plan to open it to public someday, although the time has not yet been set.

By the way, you can refer to the specific procedure for generating a vulnerability database in my paper S&P`17 paper (https://ccs.korea.ac.kr/pds/SNP17.pdf), and reproduce it. Hope it helps.
