### ISSUE TITLE
Reproducing the result

### ISSUE THREAD

**Issue by faysalhossain2007** [squizz617/vuddy#14]
Hi,
I tried to reproduce your result. I start with the testcode shared in the github but it is not detecting any vulnerability once I upload it to the https://iotcube.net/process/type/wf1

Note that, I followed the procedure from https://iotcube.net/userguide/hmark.pdf

**Comment by WOOSEUNGHOON** [comment]
@faysalhossain2007 
Hi. Because the vulnerability dataset of IoTcube has been changed, no vulnerabilities are detected in the testcode.

Instead, if you use an old version of [Redis](https://github.com/redis/redis) or [OpenSSL](https://github.com/openssl/openssl) as the testing sample, you can check the detected vulnerabilities.

**Comment by faysalhossain2007** [comment]
I see. Thanks for the clarification.
